import React from "react";
import Navbar from "@/components/Navbar";
import Footer from "@/components/Footer";
import { FileText, Hammer, Book, ShieldAlert, BadgeCheck } from "lucide-react";

export default function TermsPage() {
  const terms = [
    {
        icon: <BadgeCheck className="text-blue-600" size={24} />,
        title: "Free of Charge",
        text: "Our service is provided free of charge, allowing you to create, customize, and download various types of printable paper templates.",
    },
    {
        icon: <Hammer className="text-blue-600" size={24} />,
        title: "Right to Modify",
        text: "We reserve the right to change, suspend, or terminate the service at any time without prior notice.",
    },
    {
        icon: <Book className="text-blue-600" size={24} />,
        title: "Permitted Use",
        text: "You may use the papers generated by our service for personal or educational purposes.",
    },
    {
        icon: <ShieldAlert className="text-blue-600" size={24} />,
        title: "Prohibited Use",
        text: "Do not use the generated content for illegal purposes.",
    },
    {
        icon: <FileText className="text-blue-600" size={24} />,
        title: "As Is Basis",
        text: "Our service is provided 'as is' without any express or implied warranties. You use this service at your own risk.",
    },
  ];

  return (
    <div className="flex flex-col min-h-screen">
      <Navbar />
      
      <main className="flex-1 max-w-4xl mx-auto px-6 py-20 space-y-12">
        <header className="text-center space-y-4">
            <h1 className="text-5xl font-black text-gray-900 tracking-tight sm:text-6xl">
                Terms of Use
            </h1>
            <p className="text-lg text-gray-500 max-w-2xl mx-auto">
                Simplified rules for using our platform.
            </p>
        </header>

        <section className="bg-white rounded-[2.5rem] border border-gray-100 shadow-xl overflow-hidden divide-y divide-gray-100">
            {terms.map((term, index) => (
                <div key={index} className="p-10 flex flex-col md:flex-row gap-8 items-start md:items-center hover:bg-slate-50 transition-colors group">
                    <div className="p-4 bg-slate-50 text-blue-600 rounded-[1.25rem] group-hover:bg-blue-600 group-hover:text-white transition-colors duration-300 transform scale-125 mb-4 md:mb-0">
                        {term.icon}
                    </div>
                    <div className="space-y-2">
                        <h3 className="text-2xl font-bold text-gray-900">{term.title}</h3>
                        <p className="text-gray-500 leading-relaxed text-lg">{term.text}</p>
                    </div>
                </div>
            ))}
        </section>
      </main>

      <Footer />
    </div>
  );
}
