import { PaperCategory, PaperType, PaperSettings } from '@/types/paper';

/** Layout category order (matches purpose-based UI). */
export const CATEGORIES: PaperCategory[] = [
  'Writing',
  'Music',
  'Study / Academic',
  'Productivity',
  'Work / Business',
  'Personal Development',
  'Creative',
  'Daily Life',
  'Finance',
  'Reading',
  'Travel',
  'Health',
  'Mental Health',
  'Goals',
  'Miscellaneous',
];

/**
 * Each paper type has one canonical category (for defaults, exports, and layout templates).
 * Categories may overlap in CATEGORY_TYPES so users can pick any purpose + compatible layout.
 */
export const PRIMARY_CATEGORY_FOR_TYPE: Record<PaperType, PaperCategory> = {
  blank: 'Writing',
  'vertical-lined': 'Writing',
  seyes: 'Writing',
  'split-column': 'Writing',
  'english-practice': 'Writing',
  'german-three-line': 'Writing',
  'german-three-line-border': 'Writing',
  grid: 'Study / Academic',
  dot: 'Study / Academic',
  cornell: 'Study / Academic',
  hexagonal: 'Study / Academic',
  composition: 'Study / Academic',
  arithmetic: 'Study / Academic',
  'pinyin-practice': 'Study / Academic',
  'pinyin-tianzi': 'Study / Academic',
  mizige: 'Study / Academic',
  huigongge: 'Study / Academic',
  jiugongge: 'Study / Academic',
  'tianzi-grid': 'Study / Academic',
  'cross-grid': 'Study / Academic',
  'hardpen-huigongge': 'Study / Academic',
  'pink-millimeter': 'Productivity',
  isometric: 'Productivity',
  'creative-log': 'Productivity',
  'meeting-note': 'Work / Business',
  'project-planning': 'Work / Business',
  'branded-paper': 'Work / Business',
  'minimal-journal': 'Personal Development',
  'student-note': 'Personal Development',
  'vintage-note': 'Personal Development',
  'sketch-paper': 'Creative',
  'children-drawing': 'Creative',
  storyboard: 'Creative',
  'brazilian-calligraphy': 'Creative',
  'music-staff': 'Music',
  'guitar-tab': 'Music',
  'ukulele-tab': 'Music',
  'calligraphy-music': 'Music',
};

/** Which layouts appear under each category (overlaps allowed for UX). */
export const CATEGORY_TYPES: Record<PaperCategory, PaperType[]> = {
  Writing: [
    'blank',
    'vertical-lined',
    'seyes',
    'split-column',
    'english-practice',
    'german-three-line',
    'german-three-line-border',
    'cornell',
    'dot',
  ],
  Music: ['music-staff', 'guitar-tab', 'ukulele-tab', 'calligraphy-music'],
  'Study / Academic': [
    'cornell',
    'grid',
    'dot',
    'hexagonal',
    'composition',
    'arithmetic',
    'pinyin-practice',
    'pinyin-tianzi',
    'mizige',
    'huigongge',
    'jiugongge',
    'tianzi-grid',
    'cross-grid',
    'hardpen-huigongge',
    'vertical-lined',
    'blank',
  ],
  Productivity: [
    'grid',
    'dot',
    'pink-millimeter',
    'isometric',
    'split-column',
    'vertical-lined',
    'creative-log',
    'storyboard',
  ],
  'Work / Business': [
    'meeting-note',
    'project-planning',
    'branded-paper',
    'cornell',
    'vertical-lined',
    'split-column',
    'grid',
  ],
  'Personal Development': [
    'vertical-lined',
    'blank',
    'dot',
    'grid',
    'minimal-journal',
    'student-note',
    'vintage-note',
  ],
  Creative: [
    'sketch-paper',
    'children-drawing',
    'storyboard',
    'dot',
    'isometric',
    'hexagonal',
    'brazilian-calligraphy',
    'blank',
  ],
  'Daily Life': ['grid', 'vertical-lined', 'dot', 'split-column', 'blank', 'pink-millimeter'],
  Finance: ['grid', 'pink-millimeter', 'vertical-lined', 'dot', 'split-column'],
  Reading: ['cornell', 'vertical-lined', 'grid', 'dot', 'blank'],
  Travel: ['blank', 'vertical-lined', 'dot', 'grid', 'seyes'],
  Health: ['grid', 'dot', 'vertical-lined'],
  'Mental Health': ['vertical-lined', 'blank', 'grid', 'dot', 'minimal-journal'],
  Goals: ['grid', 'vertical-lined', 'dot', 'cornell'],
  Miscellaneous: [
    'blank',
    'dot',
    'cornell',
    'hexagonal',
    'creative-log',
    'storyboard',
    'brazilian-calligraphy',
    'vintage-note',
    'pink-millimeter',
  ],
};

export function getPaperCategoryForPaperType(type: PaperType): PaperCategory {
  return PRIMARY_CATEGORY_FOR_TYPE[type] ?? 'Miscellaneous';
}

export const DEFAULT_PAPER_SETTINGS: PaperSettings = {
  category: 'Writing',
  paperType: 'blank',
  paperSize: 'A4',
  orientation: 'portrait',
  numberOfPages: 1,
  theme: 'default',

  marginTop: 10,
  marginBottom: 10,
  marginLeft: 10,
  marginRight: 10,

  lineSpacing: 8,
  lineColor: '#c0c0c0',
  lineThickness: 0.5,
  lineStyle: 'solid',

  showMarginLine: true,
  marginLineColor: '#ff9999',
  marginPosition: 25,
  showHeaderLine: true,

  gridSize: 5,
  showMajorGrid: true,
  majorEvery: 5,
  majorLineColor: '#aaaaaa',
  majorLineThickness: 1,
  dotSpacing: 5,
  dotSize: 1.5,
  dotColor: '#aaaaaa',

  splitColumnCount: 2,
  splitColumnRatio: '1:2',
  dividerLineColor: '#888888',
  cornellCueWidth: 60,
  cornellSummaryHeight: 50,
  cornellHeaderHeight: 20,
  cornellSidebarPosition: 'left',
  isometricSpacing: 10,
  hexSize: 8,
  hexFillColor: 'transparent',
  seyesUnitSize: 2,
  seyesMajorColor: '#6699ff',
  seyesHelperColor: '#aabbff',
  storyboardRows: 3,
  storyboardCols: 2,
  storyboardAspectRatio: '16:9',
  storyboardLinesPerFrame: 3,

  stavesPerPage: 8,
  staffLineSpacing: 2,
  staffColor: '#222222',
  staffLineThickness: 0.5,
  gapBetweenStaves: 15,
  showTrebleClef: false,
  tabSystemsPerPage: 6,
  tabStrings: 6,
  tabStringSpacing: 3,
  tabShowLabel: true,
  ukuleleStaffGap: 5,

  charsPerRow: 10,
  rowHeight: 14,
  cellBorderColor: '#aaaaaa',
  innerDividerColor: '#dddddd',
  innerDividerStyle: 'dashed',
  compositionRows: 20,
  compositionCols: 20,
  arithmeticCols: 4,
  arithmeticProblemHeight: 20,
  germanRowSpacing: 4,
  borderMargin: 5,
  slantAngle: 52,
  slantLineColor: '#c0c0c0',

  brandedHeaderHeight: 25,
  brandedHeaderText: 'Your Brand Name',
  brandedHeaderBg: '#1a1a2e',
  brandedHeaderTextColor: '#ffffff',
  brandedFooterText: 'www.paperyus.com',
  brandedAccentBar: true,

  backgroundColor: '#ffffff',
  opacity: 100,
  showBorder: false,
  borderColor: '#000000',
  borderThickness: 1,

  watermarkText: '',
  watermarkColor: '#000000',
  watermarkOpacity: 10,
  watermarkFontSize: 48,
  watermarkRotation: -30,

  showPageNumbers: false,
  pageNumberFormat: '- {n} -',
};
